file(REMOVE "${CASE_PATH}")
execute_process(COMMAND "${CLI}" fixture stale "${CASE_PATH}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "fixture export failed")
endif()
execute_process(COMMAND "${CLI}" replay "${CASE_PATH}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 0 OR NOT output MATCHES "SAME_FAILURE signature=stale-generation witness=1,2,3,4,5,")
  message(FATAL_ERROR "fresh exported replay failed: ${output}")
endif()
file(SHA256 "${CASE_PATH}" before)
execute_process(COMMAND "${CLI}" fixture benign "${CASE_PATH}" RESULT_VARIABLE result ERROR_VARIABLE error)
file(SHA256 "${CASE_PATH}" after)
if(NOT result EQUAL 3 OR NOT before STREQUAL after)
  message(FATAL_ERROR "fixture export overwrote an existing file")
endif()
execute_process(COMMAND "${CLI}" replay "${CASE_PATH}" other RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 2 OR NOT output MATCHES "DIFFERENT_FAILURE")
  message(FATAL_ERROR "different signature accepted")
endif()
file(REMOVE "${CASE_PATH}")
execute_process(COMMAND "${CLI}" fixture benign "${CASE_PATH}" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "benign export failed")
endif()
execute_process(COMMAND "${CLI}" replay "${CASE_PATH}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 1 OR NOT output MATCHES "NO_MATCH")
  message(FATAL_ERROR "benign sharing failed")
endif()
file(WRITE "${CASE_PATH}" "IFF 1 0 0 cpu-reference-v1 0\n")
execute_process(COMMAND "${CLI}" replay "${CASE_PATH}" RESULT_VARIABLE result OUTPUT_VARIABLE output)
if(NOT result EQUAL 4 OR NOT output MATCHES "INCONCLUSIVE")
  message(FATAL_ERROR "incomplete capture was accepted")
endif()
file(WRITE "${CASE_PATH}" "IFF 1 1 0 cpu-reference-v1 1\n")
execute_process(COMMAND "${CLI}" replay "${CASE_PATH}" RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 3 OR NOT error MATCHES "INVALID")
  message(FATAL_ERROR "truncated trace was accepted")
endif()
file(REMOVE "${CASE_PATH}")
